{% set name = "pyfqmr" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5f895ad43b6381b6b5b8780666662d02e889c2624ecfd034e2e518c779c64026

build:
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-build-isolation --no-index -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - pyfqmr
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - trimesh
  source_files:
    - tests/
    - example/

about:
  home: https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction
  summary: Mesh triangle reduction using quadrics
  description: Cython wrapper around [sp4acerat's quadrics mesh reduction algorithm](https://github.com/sp4cerat/Fast-Quadric-Mesh-Simplification)
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE-Fast-Quadric-Mesh-Simplification  # license for original C++ code (MIT)
    - LICENSE-pyfqmr  # license for this Cython wrapper (also MIT)

extra:
  recipe-maintainers:
    - stuarteberg
